@startuml
!include ./style.puml
skinparam ArrowFontStyle plain


Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant "command:AddCommandParser" as acp LOGIC_COLOR
Participant "command:AddCommand" as ac LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR


[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create acp
abp -> acp ++
create ac
acp -> ac
activate ac


alt duplicate person
ac --> abp : throw CommandException
else not duplicate
ac -> model : addPerson(toAdd)
ac -> ac : formatResult(toAdd)
ac --> acp --
acp --> abp --
abp --> logic -- : command
end
destroy ac
destroy acp

@enduml
