@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to add person;
:Logic parses arguments into Person;
:Create and execute AddCommand;
if () then ([isDuplicatePerson])
  :Display duplicate person error;
  stop
else ([else])
  :Add person to model;
  :Format success message;
  :Display success to user;
  stop
endif
@enduml
