@startuml
!include ./style.puml
skinparam ArrowFontStyle plain


Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant "command:DeleteAttributeCommandParser" as dacp LOGIC_COLOR
Participant "command:DeleteAttributeCommand" as dac LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR


[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create dacp
abp -> dacp ++: parse(arguments)
create dac
dacp -> dac
activate dac

dac -> model : getFilteredPersonList()
model --> dac -- : List<Person>



alt invalid index
dac --> abp  : throw CommandException
else valid index
dac -> dac : keysToRemove = attributeKeysToDelete ∩ person.attributeKeys
alt no matching keys
dac --> abp  : throw CommandException
else matching keys
dac -> dac : editedPerson = removeKeys(personToEdit, keysToRemove)
dac -> model : setPerson(personToEdit, editedPerson)
dac -> model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
dac --> dacp --
dacp --> abp --
abp --> logic -- : CommandResult("Removed attribute(s): <keys> from <name>")
end
end
destroy dac
destroy dacp

@enduml
