@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to delete a person
:Logic parses target index;
:Create and execute DeleteCommand;
if () then ([invalid index])
  :Display invalid index error;
  stop
else ([valid index])
  :Retrieve person and remove from model;
  :Display success to user;
  stop
endif
@enduml
