@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to delete attribute;
:Execute delete attribute command;
if () then ([invalid index])
:Display invalid index error;
stop
else ([valid index])
endif
if () then ([invalid command format])
:Display invalid command format;
stop
else ([valid command format])
endif
:Remove matching attribute(s);;
:Show updated contact list;
:Display success message to user;
stop

@enduml
