@startuml
!include ./style.puml
skinparam ArrowFontStyle plain


Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant "command:DeleteCommandParser" as dcp LOGIC_COLOR
Participant "command:DeleteCommand" as dc LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR


[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create dcp
abp -> dcp ++
create dc
dcp -> dc
activate dc


' Fetch list and validate index
dc -> model : getFilteredPersonList()
model --> dc -- : List<Person>


alt invalid index
dc --> abp : throw CommandException
else valid index
dc -> model : deletePerson(personToDelete)
dc -> dc : formatResult(personToDelete)
dc --> dcp --
dcp --> abp --
abp --> logic -- : command
end
destroy dc
destroy dcp

@enduml
