@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to edit person;
:Logic parses index and optional fields;
if () then ([empty fiield])
  :Display error about missing fields;
  stop
else ([non-empty field])
  :Create and execute EditCommand;
endif
if () then ([invalid person index])
  :Display invalid index error;
  stop
else ([valid person index])
  :Retrieve target person;
endif
if () then ([is duplicate person])
  :Display duplicate person error;
  stop
else ([else])
  :Apply edits and refresh list;
  :Display success to user;
  stop
endif
@enduml
