@startuml
!include ./style.puml
skinparam ArrowFontStyle plain


Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant "command:EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR


[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec
activate ec


' Fetch list and validate index
ec -> model : getFilteredPersonList()
model --> ec -- : List<Person>


alt invalid index
ec --> abp  : throw CommandException
else valid index
ec -> ec : personToEdit = list.get(index)
ec -> ec : editedPerson = createEditedPerson(personToEdit, descriptor)
ec -> ec : identityChanged = !personToEdit.isSamePerson(editedPerson)
alt identity changed and duplicate exists
ec --> abp  : throw CommandException
else safe to edit
ec -> model : setPerson(personToEdit, editedPerson)
ec -> model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
ec -> ec : formatResult(editedPerson)
ec --> ecp --
ecp --> abp --
abp --> logic -- : command
end
end
destroy ec
destroy ecp

@enduml
