@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to edit person;
:Logic parses index and optional fields;
if () then ([no fields to edit provided])
  :Display format error;
  stop
else ([at least one field provided])
  :Create EditCommand with EditPersonDescriptor;
endif
if () then ([invalid person index])
  :Display invalid index error;
  stop
else ([valid person index])
  :Retrieve target person;
endif
if () then ([is duplicate person])
  :Display duplicate person error;
  stop
else ([else])
  :Apply edits and refresh list;
  :Display success to user;
  stop
endif

@enduml
