@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command to filter students;
:Logic parses attribute filters;
if () then ([invalid format])
  :Display format error;
  stop
else ([valid format])
  :Create AttributeContainsPredicate;
  :Create and execute FilterCommand;
endif
:Apply predicate to filtered list;
:Display filtered students with count;
stop
@enduml

