@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters remark command;
:Execute remark command;

if () then ([invalid index])
  :Display invalid index error;
  stop
else ([valid index])
endif

if () then ([empty remark])
  :Clear remark for selected person;
else ([non-empty remark])
  :Add or update remark for selected person;
endif
:Show updated contact list;
:Display success message to user;
stop

@enduml